#!/bin/csh

####################################################################
#  Brandon Tweed
#  CSCI 330 - Unix
#  Assignment X
#  Date Due: 3-2-2004
#  Instructor: Rush
#  TA: Kons Muhtaris
#
#  Description:
#
#  This script takes either one or two arguments.
#  If one argument is specified, then this argument is used to
#  search recursively through the current directory in each
#  file to find the keyword specified.
#  If two arguments are specified, then the script will
#  search for the keyword specified as the second argument
#  inside the directory specified as the first argument.
#  If no arguments are given, the script will give an error message.
#
######################################################################

if (($#argv == 0) || ($#argv > 2)) then
    echo "Incorrect number of arguments."
    echo "This program needs at least one but not more than two."
    exit 1
endif

# if the number of arguments was one
if ($#argv == 1) then
    # search through all files in current directory
    foreach filein (`ls -R`)
       # if the item is a file, then search for the keyword
       if (-f $filein) then
           grep -l $1 $filein
       endif
    end
else
   # if the location exists
   if ( -e $1 && -d $1) then
       # if an old list of files exists, then get rid of it
       if ( -e lf.out ) then
           rm lf.out
       endif
       # find all files in that location recursively with matching word
       ((find $1 -exec grep -l -s $2 {} \;) > lf.out) >& /dev/null
       # display the list of matching files
       cat lf.out
   else
       echo "The specified directory: ($1) does not exist."
   endif
endif


